### ISSUE TITLE
JavaFX add-opens fiji.toml support

### ISSUE THREAD

**Issue by karlduderstadt** [apposed/jaunch#51]
First of all, thank you for all your awesome work on jaunch! In my testing it works as expected/described!

I have several questions about JavaFX support as fiji migrates to jaunch and Java 11 and higher. I am not sure this will be the correct place for all of them, but I hope this is a good starting place.

The GUI for our collection of Fiji tools (Mars), uses JavaFX and depends on direct access to several JavaFX classes. Starting with Java 9, we now have the module system. I had to add the following lines to the fiji.toml for the Mars GUI to have the access needed to run:
```
'JAVA:9+|--add-opens=javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED',
    'JAVA:9+|--add-opens=java.base/java.lang.reflect=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.base/com.sun.javafx.runtime=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.base/com.sun.javafx.binding=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.base/com.sun.javafx.event=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED'
```
Will it be possible to add these through update sites? Otherwise, could these be added to the fiji.toml?

When I launch fiji, with these lines added to the toml, I get the following warnings in the terminal:
```
WARNING: Unknown module: javafx.controls specified to --add-opens
WARNING: Unknown module: javafx.graphics specified to --add-opens
WARNING: Unknown module: javafx.base specified to --add-opens
WARNING: Unknown module: javafx.controls specified to --add-opens
WARNING: Unknown module: javafx.graphics specified to --add-opens
WARNING: Unknown module: javafx.base specified to --add-opens
WARNING: Unknown module: javafx.base specified to --add-opens
WARNING: Unknown module: javafx.controls specified to --add-opens
WARNING: Unknown module: javafx.graphics specified to --add-opens
```
I think I get these warning became now the JavaFX jars are no longer bundled with the JDK, but instead are now in the jars folder. I think the jars in the jars folder haven't yet been added to the class path during startup and perhaps this is why I receive these warnings.

Is there a way to prevent these warning from happening?

On my M2 Mac Studio machine, when compiling mars-fx in IntelliJ IDEA using the following [pom](https://github.com/duderstadt-lab/mars-fx/blob/JDK11_2023/pom.xml), the following jars are added to the jars folder:
```
javafx-base-21-mac-aarch64.jar
javafx-base-21.jar
javafx-controls-21-mac-aarch64.jar
javafx-controls-21.jar
javafx-fxml-21-mac-aarch64.jar
javafx-fxml-21.jar
javafx-graphics-21-mac-aarch64.jar
javafx-graphics-21.jar
javafx-media-21-mac-aarch64.jar
javafx-media-21.jar
javafx-swing-21-mac-aarch64.jar
javafx-swing-21.jar
javafx-web-21-mac-aarch64.jar
javafx-web-21.jar
javafxsvg-1.3.0.jar
```
It seems the jars will depend on the java version as well as possibly the computer architecture. How should these jars be distributed? Can I somehow help with testing/evaluating what should be done? (maybe I should post this question elsewhere, but I am not really sure where)

**Comment by ctrueden** [comment]
> Will it be possible to add these through update sites?

Yes, issue #38 tracks the need for this.

> Is there a way to prevent these warning from happening?

Java now has the module path as well as the classpath. Maybe if you add those JavaFX JARs to the module path, it will work. Right now, the fiji.toml Jaunch configuration adds only the imagej-launcher JAR to the classpath—unless you pass the `--full-classpath` flag, or run in `--python` mode, in which case it puts all JARs in `jars/*/*.jar` and `plugins/*.jar` on the classpath. But in no case does Jaunch put anything on the module path right now. It may be that simply having them on the classpath at startup is sufficient to quelch the warnings. Do you see the warnings when you run in Python mode and/or with the `--full-classpath` flag? You can use the `--dry-run` flag to see exactly how Jaunch is launching Java under the hood.

> It seems the jars will depend on the java version as well as possibly the computer architecture. How should these jars be distributed?

Platform-specific JARs go into a subfolder of `jars`. For mac-aarch64, it'll be `jars/macosx-arm64`. The Updater is smart enough to mark JAR files in the platform-specific folders as specific to the respective platform in the `db.xml` metadata, meaning that only Fiji installations running on the matching platform will download them.

**Comment by karlduderstadt** [comment]
Thanks for the prompt feedback. Sorry I was so slow to reply.

> Yes, issue #38 tracks the need for this.
Wonderful! I didn't realize there was already an issue.

> Or, it may be that simply having them on the classpath at startup is sufficient to quelch the warnings. Do you see the warnings when you run in Python mode and/or with the `--full-classpath` flag? 
I tried using `--full-classpath` in different combinations with or without python. In all cases, I am still getting the warnings. I also added the `--dry-run` flag and I can see all the jars are added. However, I still get the warnings. This surprises me. I will keep testing.

> Platform-specific JARs go into a subfolder of `jars`. For mac-aarch64, it'll be `jars/macosx-arm64`. The Updater is smart enough to mark JAR files in the platform-specific folders as specific to the respective platform in the `db.xml` metadata, meaning that only Fiji installations running on the matching platform will download them.
This sounds like a great solution. I didn't know about this.

Sounds like all the important details are being worked on. The warning are a minor issue and not urgent, but I guess in the long run it would be nice if there were no warnings. I will keep exploring.

**Comment by karlduderstadt** [comment]
Here is the full set of lines that would need to be added to the fiji.toml file based on our discussion on the forum (https://forum.image.sc/t/how-best-to-manage-javafx-dependencies/110927/11). Seems like a lot, but all appear to be required in my testing. I do wonder if this usage limits the ability to use the module-path for other applications. I hope you can just add to it.

```
# Make JavaFX dependencies work without complaint.
    'JAVA:9+|--module-path=${app-dir}/jars/mac-aarch64',
    'JAVA:9+|--add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.web',
    'JAVA:9+|--add-opens=javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED',
    'JAVA:9+|--add-opens=java.base/java.lang.reflect=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.base/com.sun.javafx.runtime=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.base/com.sun.javafx.binding=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.base/com.sun.javafx.event=ALL-UNNAMED',
    'JAVA:9+|--add-opens=javafx.graphics/com.sun.javafx.stage=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.base/com.sun.javafx.logging=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.javafx.util=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.glass.utils=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.javafx.embed=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.javafx.geom=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.javafx.geom.transform=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.javafx.sg.prism=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.swing/javafx.embed.swing=ALL-UNNAMED',
    'JAVA:9+|--add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED',
```

**Comment by ctrueden** [comment]
With fiji/fiji@5845b2f8e8f6a31892425421fbc69831b2176ba9, I consider this issue thoroughly addressed on the Fiji side.

**Comment by karlduderstadt** [comment]
I just downloaded a new Fiji and updated everything. Unfortunately, now I am once again getting the unnamed module error when just trying to open a MARS archive:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class javafx.embed.swing.JFXPanel (in unnamed module @0x4550bb58) cannot access class com.sun.javafx.logging.PlatformLogger (in module javafx.base) because module javafx.base does not export com.sun.javafx.logging to unnamed module @0x4550bb58
	at javafx.embed.swing.JFXPanel.<clinit>(JFXPanel.java:148)
	at de.mpg.biochem.mars.fx.molecule.AbstractMoleculeArchiveFxFrame.init(AbstractMoleculeArchiveFxFrame.java:211)
	at de.mpg.biochem.mars.fx.molecule.DnaMoleculeArchiveFxView.view(DnaMoleculeArchiveFxView.java:69)
	at org.scijava.ui.AbstractUserInterface$1.run(AbstractUserInterface.java:139)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:233)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
So, I guess somehow it is not adding what is required. How did you test it out? Do you have a suggestion of how I should test it?

I moved our update MARS that works with Fiji-Latest to the main branch at mars-fx (I ended up force pushing to sync the branch 😢 ). Should I test with some other JavaFX program?

**Comment by ctrueden** [comment]
> I guess somehow it is not adding what is required.

Yeah, it seems like not all packages get opened successfully.

Sorry for the hassle. For now, I uploaded another `fiji.toml` with all the `--add-opens` and `--add-exports` restored. I'll do more testing when I have time to understand better the best way forward here.

**Comment by ctrueden** [comment]
The issue turned out to be that I forgot `-Dscijava.app.unlock-modules=true` in the TOML config. Once I included that (fiji/fiji@14d40f0c932350c3c87ed7b256ccddfca17bcd4b), the SciJava app-launcher ReflectionUnlocker does do its job as we hoped. So the TOML config is slimmer again now.
